### ISSUE TITLE
КОД

### ISSUE THREAD

**Issue by kzagorulko** [Ivan753/mirea-work-7s#2]
https://github.com/Ivan753/mirea-work-7s/blob/653267d651ab3eae0db8b1ad2b5422fe4bb50c7d/is/playfair_chiper.py#L3

```python
ALPHABET = [
    'А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ж', 'З', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П',
    'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Щ', 'Ъ', 'Ы', 'Э', 'Ю', 'Я',
]

SYMBOL = 'А'

SYMBOLS_FOR_REPLACE = {'Ь': 'Ъ', 'Й': 'И', 'Ё': 'Е'}


def replace_symbols(symbol):
    return (
        symbol in SYMBOLS_FOR_REPLACE and SYMBOLS_FOR_REPLACE[symbol] or symbol
    )


def make_matrix(word):
    word_in_list = [replace_symbols(b) for b in word]
    alphabet = word_in_list + list(
        filter(lambda b: b not in word_in_list, ALPHABET)
    )

    while len(alphabet) > 0:
        yield alphabet[:6]
        alphabet = alphabet[6:]


def get_row_and_column(letter, matrix):
    i = 0
    while letter not in matrix[i]:
        i += 1
    return i, matrix[i].index(letter)


def get_dual(dual, matrix, action):
    if action == 'encrypt':
        foo = 1
    elif action == 'decrypt':
        foo = -1
    else:
        raise ValueError

    def _get_letter_info(letter):
        row, column = get_row_and_column(letter, matrix)
        return {
            'letter': letter,
            'row': row,
            'column': column,
        }

    first_letter = _get_letter_info(dual[0])
    second_letter = _get_letter_info(len(dual) > 1 and dual[1] or SYMBOL)

    if first_letter['row'] == second_letter['row']:
        def _calc(_column):
            return (_column + 6 + foo) % 6
        return (
            matrix[first_letter['row']][_calc(first_letter['column'])]
            + matrix[second_letter['row']][_calc(second_letter['column'])]
        )
    elif first_letter['column'] == second_letter['column']:
        def _calc(row):
            return (row + 5 + foo) % 5
        return (
            matrix[_calc(first_letter['row'])][first_letter['column']]
            + matrix[_calc(second_letter['row'])][second_letter['column']]
        )
    return (
        matrix[first_letter['row']][second_letter['column']]
        + matrix[second_letter['row']][first_letter['column']]
    )


def main():
    alphabet_set = set(ALPHABET + list(SYMBOLS_FOR_REPLACE.keys()))

    key_word = input('Введите кодовое слово: ')
    key_word_set = set(key_word)
    if not key_word_set.issubset(alphabet_set):
        raise ValueError('Кодовое слово содержит недопустимые символы')
    if len(key_word) != len(key_word_set):
        raise ValueError('Кодовое слово содержит повторяющиеся символы')

    encrypted_text = [replace_symbols(s) for s in input('Введите текст: ')]
    if not set(encrypted_text).issubset(alphabet_set):
        raise ValueError('Текст содержит недопустимые символы')
    if len(encrypted_text) % 2 == 1:
        raise ValueError('Некорректная длинна текста')

    matrix = list(make_matrix(key_word))

    spliced_text = [
        encrypted_text[i:i + 2] for i in range(0, len(encrypted_text), 2)
    ]

    for dual in spliced_text:
        print(get_dual(dual, matrix, 'decrypt'), end='')

    print()

    decrypted_text = [
        replace_symbols(s) for s in input('Введите текст для шифрования: ')
    ]
    if not set(decrypted_text).issubset(alphabet_set):
        raise ValueError('Текст содержит недопустимые символы')
    spliced_text = [
        decrypted_text[i:i + 2] for i in range(0, len(decrypted_text), 2)
    ]

    for dual in spliced_text:
        print(get_dual(dual, matrix, 'encrypt'), end='')


if __name__ == '__main__':
    try:
        main()
    except ValueError as e:
        print(e)

```

**Comment by Ivan753** [comment]
- ни одного комментария
- код плохо читается
- используются глобальные переменные

**Comment by jagerwil** [comment]
![image](https://user-images.githubusercontent.com/31615013/93716236-57be7100-fb77-11ea-8ecd-67c9ddbb58e9.png)
fooooooo

**Comment by jagerwil** [comment]
![image](https://user-images.githubusercontent.com/31615013/93716252-66a52380-fb77-11ea-8ab3-92f4baa12f71.png)
![image](https://user-images.githubusercontent.com/31615013/93716256-6e64c800-fb77-11ea-8da8-d717081d06ec.png)
Здесь для понимания надо реально посидеть и повтыкать, выглядит монструозно ебана рот (за мат извени)

**Comment by jagerwil** [comment]
![image](https://user-images.githubusercontent.com/31615013/93716307-bb489e80-fb77-11ea-9cb1-6414f5ee2127.png)
и тут прибегает почта россии

**Comment by jagerwil** [comment]
![image](https://user-images.githubusercontent.com/31615013/93716357-02369400-fb78-11ea-9fdc-ac01f64b8a45.png)
так стоп, а зачем дуал получать, вот же он

**Comment by jagerwil** [comment]
![image](https://user-images.githubusercontent.com/31615013/93716504-e384cd00-fb78-11ea-8410-2c6b2615aaf7.png)
Природа настолько очистилась, что скобочки с лиспа вернулись в питон

**Comment by kzagorulko** [comment]
> ![image](https://user-images.githubusercontent.com/31615013/93716252-66a52380-fb77-11ea-8ab3-92f4baa12f71.png)
> ![image](https://user-images.githubusercontent.com/31615013/93716256-6e64c800-fb77-11ea-8da8-d717081d06ec.png)
> Здесь для понимания надо реально посидеть и повтыкать, выглядит монструозно ебана рот (за мат извени)

во что? Не знаешь как работает and и or? и как списки складываются?

**Comment by jagerwil** [comment]
понимаю, но это выглядит страшно


> > ![image](https://user-images.githubusercontent.com/31615013/93716252-66a52380-fb77-11ea-8ab3-92f4baa12f71.png)
> > ![image](https://user-images.githubusercontent.com/31615013/93716256-6e64c800-fb77-11ea-8da8-d717081d06ec.png)
> > Здесь для понимания надо реально посидеть и повтыкать, выглядит монструозно ебана рот (за мат извени)
> 
> во что? Не знаешь как работает and и or? и как списки складываются?

**Comment by kzagorulko** [comment]
> понимаю, но это выглядит страшно
> 
> > > ![image](https://user-images.githubusercontent.com/31615013/93716252-66a52380-fb77-11ea-8ab3-92f4baa12f71.png)
> > > ![image](https://user-images.githubusercontent.com/31615013/93716256-6e64c800-fb77-11ea-8da8-d717081d06ec.png)
> > > Здесь для понимания надо реально посидеть и повтыкать, выглядит монструозно ебана рот (за мат извени)
> > 
> > 
> > во что? Не знаешь как работает and и or? и как списки складываются?

это энд и ор, это мировая практика 
Понимаю, сложение листов обычно делают через жопу, но так можно

**Comment by kzagorulko** [comment]
> ![image](https://user-images.githubusercontent.com/31615013/93716504-e384cd00-fb78-11ea-8410-2c6b2615aaf7.png)
> Природа настолько очистилась, что скобочки с лиспа вернулись в питон

> 
![image](https://user-images.githubusercontent.com/31614542/93716673-d0263180-fb79-11ea-8d82-a03ede0a0392.png)

**Comment by jagerwil** [comment]
> > ![image](https://user-images.githubusercontent.com/31615013/93716504-e384cd00-fb78-11ea-8410-2c6b2615aaf7.png)
> > Природа настолько очистилась, что скобочки с лиспа вернулись в питон
> 
> > 
> 
> ![image](https://user-images.githubusercontent.com/31614542/93716673-d0263180-fb79-11ea-8d82-a03ede0a0392.png)

я ваньку это тоже говорил

**Comment by jagerwil** [comment]
![image](https://user-images.githubusercontent.com/31615013/93716784-39a64000-fb7a-11ea-9ae3-363ece2d7d45.png)
Не совсем понятно, для чего вообще alphabet_set, ведь у тебя уже есть функция replace_symbols, которая может конвертировать вводную строку в строку, в которой содержатся только символы из алфавита

**Comment by jagerwil** [comment]
Еще непонятно, для чего внизу этого скрина нужна проверка на недопустимые символы

**Comment by kzagorulko** [comment]
> ![image](https://user-images.githubusercontent.com/31615013/93716784-39a64000-fb7a-11ea-9ae3-363ece2d7d45.png)
> Не совсем понятно, для чего вообще alphabet_set, ведь у тебя уже есть функция replace_symbols, которая может конвертировать вводную строку в строку, в которой содержатся только символы из алфавита

а если приедет нелегальный символ типа R или пробел? Плюс это множество включает все легальные символы

**Comment by kzagorulko** [comment]
> Еще непонятно, для чего внизу этого скрина нужна проверка на недопустимые символы

защита от дурака

**Comment by jagerwil** [comment]
> > ![image](https://user-images.githubusercontent.com/31615013/93716784-39a64000-fb7a-11ea-9ae3-363ece2d7d45.png)
> > Не совсем понятно, для чего вообще alphabet_set, ведь у тебя уже есть функция replace_symbols, которая может конвертировать вводную строку в строку, в которой содержатся только символы из алфавита
> 
> а если приедет нелегальный символ типа R или пробел? Плюс это множество включает все легальные символы

можно для key_word сделать replace_symbols, а потом проверить key_word на то, являются ли его буквы частью списка ALPHABET. Тогда alphabet_set вообще не нужен

**Comment by kzagorulko** [comment]
оно по логике не может содержать этих букв, насколько я понимаю

**Comment by jagerwil** [comment]
пофиксил предыдущий коммент

**Comment by jagerwil** [comment]
пофиксил предыдущий коммент о том, что пофиксил предпредыдущий коммент

**Comment by Ivan753** [comment]
Работаем дальше

**Comment by kzagorulko** [comment]
Ладно
